
name = "open23-hugo-theme"
license = "MIT"
licenselink = "https://github.com/open-23/hugo-open23/blob/master/LICENSE"
description = "Open23 Hugo – App Landing Page is the perfect app showcase Hugo Theme. Open23 is a better way to present your modern business and app showcasing. It’s easy to customize and also well documented. And compatible with Desktop, laptop, mobile, and also compatible with major browsers. We follow the modern design system to craft the template. Open23 is based of the Apsho Theme."
homepage = "https://open23.de"
tags = ['clean', 'minimal', 'agency', 'corporate', 'creative agency', 'creative studio', 'portfolio', 'staticmania', 'responsive', 'blog', 'customizable', 'company', 'creative', 'agency template']
features = ['responsive design', 'blog', 'responsive','landing-page', 'minimal', 'business', 'agency-template', 'hugo-theme', 'portfolio', 'company', 'creative', 'contact-form']
min_version = "0.41.0"

[author]
  name = "Sabina Sadowski"
  homepage = "https://ssadowski.de/"
